version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.2.0
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Building the Next.js app...
      - npm run build
  build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
